name: Release beta

on: [ workflow_dispatch ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Binary
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
 
      - name: cargo plugin cache
        id: cargo-plugin-cache
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-plugins

      - name: install cargo plugin
        if: steps.cargo-plugin-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-release

      - name: Beta Release
        run: |
          git config --global user.email "ruimo.uno@gmail.com"
          git config --global user.name "Shisei Hanai"
          cargo release -vv beta --execute --no-publish --no-confirm
